spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/transrota
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

logging.level.org.flywaydb=INFO
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.com.transrota.backend=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} level=%-5level correlationId=%X{correlationId:-none} logger=%logger{36} - %msg%n
